### PR TITLE
Fix ARP and NDP next-hop detection with RSS

### LINKED ISSUE #981: Next-hop discovery versus RSS
Hi!

The point of RSS is to allow multiple worker processes to transparently and independently extend the capacity of a network function by adding more cores behind an interface: more wood behind the arrow instead of more arrows, effectively.  This strategy is obviously at odds with any kind of state that needs to be shared between processes, and any assumption that a packet sent by an RSS process will result in a reply from a remote server back to that RSS process.

Indeed, ltietz found that with multiple queues and RSS, some RSS workers were not finding the next hop.  Sometimes the problems were with ARP, and sometimes they were with NDP.  We need to fix next-hop resolution to work in the presence of multiple workers, only one of which probably will receive the reply.

Options: top-down configuration; a back-channel between apps and processes via the file system (I like this one best); dunno.

### PR DESCRIPTION
**Pull request by wingo**
Attempt to fix #981 by having the ARP app that receives an ARP response write that MAC to shared memory.  Likewise for NDP.  When apps are still resolving addresses, they will try to read from a shared file also.

### CODE REVIEW

File: src/apps/ipv4/arp.lua [hunk 1]
```diff
@@ -182,11 +190,28 @@ function ARP:send_arp_request (output)
...
 
-function ARP:arp_resolved (ip, mac)
+function ARP:arp_resolved (ip, mac, provenance)
    print(("ARP: '%s' resolved (%s)"):format(ipv4:ntop(ip), ethernet:ntop(mac)))
    if self.alarm_notification then
       resolve_alarm:clear()
    end
+   self.next_mac = mac
+   if self.shared_next_mac_key then
+      local ok, shared_mac = pcall(shm.create, self.shared_next_mac_key, mac_t)
```
Comment (takikawa) [inline src/apps/ipv4/arp.lua]: Does `shared_mac` need to be `shm.unmap`ed at the end of the block or is it ok to leave it?

**Review by takikawa — APPROVED** [review]
LGTM (one minor nit commented)
