### PR TITLE
Fix packet allocation overflow

### LINKED ISSUE #527: Crash caused by packet allocation overflow
How to reproduce:

``` bash
$ sudo ./snabb lwaftr soaktest -D 60 data/icmp_on_fail.conf \
   data/tcp-frominet-bound-ttl1.pcap data/empty.pcap
loading compiled binding table from data/binding-table.o
compiled binding table data/binding-table.o is up to date.
core/main.lua:26: packet allocation overflow
stack traceback:
        core/main.lua:137: in function <core/main.lua:135>
        [C]: in function 'error'
        core/main.lua:26: in function 'assert'
        core/packet.lua:193: in function 'preallocate_step'
        core/packet.lua:86: in function 'allocate'
        core/packet.lua:165: in function 'clone'
        apps/basic/basic_apps.lua:130: in function 'method'
        core/app.lua:87: in function 'with_restart'
        core/app.lua:319: in function 'thunk'
        core/histogram.lua:98: in function 'breathe'
        core/app.lua:273: in function 'main'
        program/lwaftr/soaktest/soaktest.lua:46: in function 'run'
        program/lwaftr/lwaftr.lua:17: in function 'run'
        core/main.lua:56: in function <core/main.lua:43>
        [C]: in function 'xpcall'
        core/main.lua:179: in main chunk
        [C]: at 0x00452c40
        [C]: in function 'pcall'
        core/startup.lua:3: in main chunk
        [C]: in function 'require'
        [string "require "core.startup""]:1: in main chunk
```

Possibly same cause as #516

### PR DESCRIPTION
**Pull request by dpino**
Origin packet must be always dropped in `transmit_icmpv4_reply`, and not only if the about-to-be-sent packet can be transmitted. Not dropping the packet causes more packet allocation in packet.free_list, which eventually leads to packet allocation overflow when no more packets can be allocated in packet.free_list.

The PR also allows to passing `duration` to soaktest.sh script and fixes an issue with duration in soaktest.lua, necessary to run to reproduce #527.

This PR fixes #527.

### CODE REVIEW

File: src/program/lwaftr/tests/soaktest/core-soaktest.sh [hunk 1]
```diff
@@ -13,10 +15,10 @@ function quit_with_msg {
...
 function soaktest {
     conf="$1"; in_v4="$2"; in_v6="$3"
-    $SNABB_LWAFTR soaktest "$conf" "$in_v4" "$in_v6" ||
-        quit_with_msg $? "Test failed: $SNABB_LWAFTR soaktest $@"
-    $SNABB_LWAFTR soaktest --on-a-stick "$conf" "$in_v4" "$in_v6" ||
-        quit_with_msg $? "Test failed: $SNABB_LWAFTR soaktest --on-a-stick $@"
+    $SNABB_LWAFTR soaktest -D $DURATION "$conf" "$in_v4" "$in_v6" ||
+        quit_with_msg $? "$SNABB_LWAFTR soaktest -D $DURATION $conf $in_v4 $in_v6"
+    $SNABB_LWAFTR soaktest -D $DURATION --on-a-stick "$conf" "$in_v4" "$in_v6" ||
+        quit_with_msg $? "$SNABB_LWAFTR soaktest -D $DURATION --on-a-stick $conf $in_v4 $in_v6"
```
Comment (kbara) [inline src/program/lwaftr/tests/soaktest/core-soaktest.sh:21]: When running, does this new wording still make it clear that a test failed, in all of the ways soak tests are invoked, including running just them?

**Comment by kbara** [comment]
Aside from wording nit, LGTM

File: src/program/lwaftr/tests/soaktest/core-soaktest.sh (hunk 1 above)
Comment (dpino) [reply src/program/lwaftr/tests/soaktest/core-soaktest.sh:21]: Yes, actually it's a fix. With the former code that used $@, more parameters than needed where shown so when trying to run the test case it failed cause `lwaftr soaktest` expects 3 parameters only: conf, in_ipv4 and ip_ipv6. 

Before the failing command shown 7 parameters because this function actually receives that many parameters. Function `read_test_data` reads test data in groups of 7 parameters, necessary for running end-to-end test cases too. The relevant line is this one:

https://github.com/Igalia/snabb/blob/lwaftr/src/program/lwaftr/tests/soaktest/core-soaktest.sh#L29

Comment (kbara) [reply src/program/lwaftr/tests/soaktest/core-soaktest.sh:21]: I don't mean $@ vs the current variables, I mean the removal of the phrase "Test failed" at the beginning.

Comment (dpino) [reply src/program/lwaftr/tests/soaktest/core-soaktest.sh:21]: Yes, the change is correct. `quit_with_msg` already prints out "Test failed". The message was duplicated.

**Comment by wingo** [comment]
@kbara since Diego is on holiday, would you mind merging this please?  Thanks :)  (I ask you since you did the review)
