### PR TITLE
Respond to ping6 packets in on-a-stick mode

### LINKED ISSUE #709: Stack Traceback when running with -onastick
Hi, 

I'm seeing a problem with starting the lwaftr when -onastick is used.

**service lwaftr start**

```bash
Starting lwaftr: 
root@bn831-dcdev-10a-lab:/opt/snabb/conf#  /opt/snabb/conf/lwaftr-315-onastick.conf: loading compiled configuration from /opt/snabb/conf/lwaftr-315-onastick.o
/opt/snabb/conf/lwaftr-315-onastick.conf: compiled configuration is up to date.
Bound main process to NUMA node: 	0
Bound data plane to CPU:	6
apps/lwaftr/ipv6_apps.lua:145: Could not resolve IPv6 address: 2003:1b0b:fffd:831::1
stack traceback:
	core/main.lua:149: in function <core/main.lua:147>
	[C]: in function 'error'
	apps/lwaftr/ipv6_apps.lua:145: in function 'maybe_send_ns_request'
	apps/lwaftr/ipv6_apps.lua:167: in function 'method'
	core/app.lua:89: in function 'with_restart'
	core/app.lua:463: in function 'thunk'
	core/histogram.lua:98: in function 'breathe'
	core/app.lua:410: in function 'main'
	program/lwaftr/setup.lua:507: in function 'run_worker'
	[string "require('program.lwaftr.setup').run_worker({[..."]:1: in function 'f'
	core/main.lua:58: in function <core/main.lua:43>
	[C]: in function 'xpcall'
	core/main.lua:211: in main chunk
	[C]: at 0x00452d30
	[C]: in function 'pcall'
	core/startup.lua:3: in main chunk
	[C]: in function 'require'
	[string "require "core.startup""]:1: in main chunk
```

Here's the config of the attached router interface (Cisco ASR9k - works fine using same config params(other interface) when not onastick):

```
RP/0/RSP0/CPU0:bn831x1-r2-29-1a-lab#show run int te 0/2/0/0.125
Thu Jan 12 11:25:10.056 UTC
interface TenGigE0/2/0/0.125
 ipv6 nd suppress-ra
 ipv6 address 2003:1b0b:fffd:831::1/64
 ipv6 enable
 encapsulation dot1q 125
!
```

And the relevant part of the .conf file for the lwaftr
 
And interfaces part of the .conf file:
```
   external-interface {
    error-rate-limiting {
      packets 600000;
    }
    ip 198.19.100.2;
    mac 52:52:00:00:00:01;
    mtu 1500;
    next-hop {
      ip 198.19.100.1;
    }
    reassembly {
      max-fragments-per-packet 40;
    }
    vlan-tag 164;
  }
  internal-interface {
    error-rate-limiting {
      packets 6000;
      period 4;
    }
    ip 2003:1b0b:fffd:831::4000;
    mac 52:52:00:00:00:02;
    mtu 9220;
    next-hop {
      ip 2003:1b0b:fffd:831::1;
    }
    reassembly {
      max-fragments-per-packet 40;
    }
    vlan-tag 125;
  }
```

I also tried replacing the next-hop ipv6 address with a MAC address:

```
  internal-interface {
    error-rate-limiting {
      packets 6000;
      period 4;
    }
    ip 2003:1b0b:fffd:831::4000;
    mac 52:52:00:00:00:02;
    mtu 9220;
    next-hop {
      mac 04:6c:9d:59:e8:e8;
    }
    reassembly {
      max-fragments-per-packet 40;
    }
    vlan-tag 125;
  }
```

This results in:  **./lwaftr-onastick.sh**

```bash
/opt/snabb/conf/lwaftr-315-onastick.conf: loading compiled configuration from /opt/snabb/conf/lwaftr-315-onastick.o
/opt/snabb/conf/lwaftr-315-onastick.conf: compiled configuration is out of date; recompiling.
/opt/snabb/conf/lwaftr-315-onastick.conf: loading source configuration
/opt/snabb/conf/lwaftr-315-onastick.conf: wrote compiled configuration /opt/snabb/conf/lwaftr-315-onastick.o
Bound main process to NUMA node: 	0
apps/config/channel.lua:54: error opening file "/var/run/snabb/4162/config-follower-channel": No such file or directory
stack traceback:
	core/main.lua:149: in function <core/main.lua:147>
	[C]: in function 'error'
	apps/config/channel.lua:54: in function 'open_ring_buffer'
	apps/config/channel.lua:103: in function 'open'
	apps/config/leader.lua:659: in function 'send_messages_to_followers'
	apps/config/leader.lua:680: in function 'method'
	core/app.lua:89: in function 'with_restart'
	core/app.lua:454: in function 'thunk'
	core/histogram.lua:98: in function 'breathe'
	core/app.lua:410: in function 'main'
	program/lwaftr/run/run.lua:221: in function 'run'
	program/lwaftr/lwaftr.lua:17: in function 'run'
	core/main.lua:67: in function <core/main.lua:43>
	[C]: in function 'xpcall'
	core/main.lua:211: in main chunk
	[C]: at 0x00452d30
	[C]: in function 'pcall'
	core/startup.lua:3: in main chunk
	[C]: in function 'require'
	[string "require "core.startup""]:1: in main chunk
```

Thanks,
Ian

### PR DESCRIPTION
**Pull request by dpino**
Fixes #709.

The lwAFTR was ignoring VLAN tag settings when running in on-a-stick mode. That can be inferred from #709 stacktrace:

```
apps/lwaftr/ipv6_apps.lua:145: Could not resolve IPv6 address: 2003:1b0b:fffd:831::1
stack traceback:
	core/main.lua:149: in function <core/main.lua:147>
```

To confirm that, I run a ping6 test with VLAN tags to the lwAFTR in on-a-stick mode. Indeed, there were no replies. 

The problem was that a function necessary for VLAN set up in on-a-stick mode was using the former configuration naming. Fixed.

### CODE REVIEW

File: src/program/lwaftr/run/run.lua [hunk 1]
```diff
@@ -124,9 +124,10 @@ end
 -- Requires a V4V6 splitter iff:
 --   Always when running in on-a-stick mode, except if v4_vlan_tag != v6_vlan_tag.
 local function requires_splitter (opts, conf)
-   if not opts["on-a-stick"] then return false end
-   if not conf.vlan_tagging then return true end
-   return conf.v4_vlan_tag == conf.v6_vlan_tag
+   if not opts["on-a-stick"] then return true end
```
Comment (teknico) [inline src/program/lwaftr/run/run.lua]: This inverts the previous behavior, and is not in accordance with the above comment anymore. Who's right, the comment or the code?

File: src/program/lwaftr/run/run.lua [hunk 2]
```diff
@@ -124,9 +124,10 @@ end
...
+   local internal_interface = conf.softwire_config.internal_interface
+   local external_interface = conf.softwire_config.external_interface
```
Comment (teknico) [inline src/program/lwaftr/run/run.lua]: We only use these two locals once, are they useful? Can't we just say this?
```
return conf.softwire_config.internal_interface.vlan_tag == conf.softwire_config.external_interface.vlan_tag
```

**Review by teknico — COMMENTED** [review]
Not clear about the new behavior.

File: src/program/lwaftr/run/run.lua (hunk 2 above)
Comment (teknico) [reply src/program/lwaftr/run/run.lua]: Or maybe:
```
local softwire_config = conf.softwire_config
return softwire_config.internal_interface.vlan_tag == softwire_config.external_interface.vlan_tag
```

File: src/program/lwaftr/run/run.lua (hunk 1 above)
Comment (dpino) [reply src/program/lwaftr/run/run.lua]: Good catch, that was a non intended change.

File: src/program/lwaftr/run/run.lua (hunk 2 above)
Comment (dpino) [reply src/program/lwaftr/run/run.lua]: Yep, although as the path is so long it breaks the 80-column wrapping, in theory the codebase should respect. Other snippets of code cache these variables too, such as https://github.com/Igalia/snabb/blob/lwaftr/src/program/lwaftr/setup.lua#L33 I followed the same pattern.

Comment (teknico) [reply src/program/lwaftr/run/run.lua]: In that other case there are many uses of these locals, so they are useful.

In this case, my second suggestion at least has two uses of `softwire_config`. :-)

True, the resulting line is longer than 80 chars. Do we have guidelines? The codebase has many lines longer than that.

Comment (dpino) [reply src/program/lwaftr/run/run.lua]: Yes, Snabb codebase has guidelines. There used to be a document with these guidelines, which mostly follow the Lua guidelines, but I cannot find it anymore. One of the guidelines was the 80-colum wrap, which most of the codebase follows, although there's code that don't.

**Comment by dpino** [comment]
Added a test to test pings from a Linux kernel interface. Example:

```bash
$ sudo SNABB_PCI0=0000:03:00.1 SNABB_PCI1=0000:83:00.1 program/lwaftr/tests/hw/selftest.sh 
Success: Ping to internal interface
Success: Ping to external interface
```

File: src/program/lwaftr/run/run.lua [hunk 3]
```diff
@@ -121,12 +121,15 @@ function parse_args(args)
...
 local function requires_splitter (opts, conf)
-   if not opts["on-a-stick"] then return false end
-   if not conf.vlan_tagging then return true end
-   return conf.v4_vlan_tag == conf.v6_vlan_tag
+   if opts["on-a-stick"] then
+      local internal_interface = conf.softwire_config.internal_interface
+      local external_interface = conf.softwire_config.external_interface
+      return internal_interface.vlan_tag == external_interface.vlan_tag
+   end
+   return false
```
Comment (teknico) [inline src/program/lwaftr/run/run.lua:132]: Thank you, much clearer this way.

**Review by teknico — APPROVED** [review]
Thanks for adding the test too. LGTM.

**Comment by dpino** [comment]
The test cannot be run inside a container for several reasons, the most important is not being able to enable a kernel-managed interface inside the container. Fixing this issue will require more investigation work.

The test works when launched manually and it's worth to keep it to test a lwAFTR responds to pings from other devices successfully.
