### PR TITLE
Fix selection of modes based on instance config

### LINKED ISSUE #957: Support --on-a-stick with multiple instances
Multiple-instance --on-a-stick doesn't right now.  Thing is, you need to specify --on-a-stick on the command line in order to set up the app graph.  This is fine when you have just one device and you want to migrate an existing configuration, but if devices are specified in the configuration, it should be possible to deduce automatically how to run the instances; if no "device" is specified on the external-interface items, then it's on a stick.

So really we have three modes of operation:

 * user specified --v4 and --v6 pci addresses and not --on-a-stick: migrate config to single-instance bump-in-the-wire.  This works.

 * user specified --on-a-stick but not --v4 or --v6: migrate config to single-instance on-a-stick.  This works.

 * None of --v4/--v6/--on-a-stick specified.  Individual instances are on-a-stick or bump-in-the-wire or not, depending on whether external-interface has a device.  This doesn't work right now; currently in this case we assume bump-in-the-wire for all.

### PR DESCRIPTION
**Pull request by tsyesika**
This fixes #957.

As #957 states there is a migration when `--on-a-stick` or `--v4`/`--v6` is specified however it doesn't allow you to run in multiprocessing mode. The problem actually ended up being deeper than that. When you did provide one of these flags (or lack there of) it'd pick the appropriate mode based on the initial configuration and command line arguments and use that for everything. That means when a `snabb config add` command was issued, it will use whatever was appropriate when it initially started irregardless of what the configuration says.

The fix changes how the `setup_fn` we pass to `setup.reconfiguration` and thus the leader works. Instead of giving it for example `setup.load_phy` or `setup.load_on_a_stick`, etc. it provides a single setup_fn which takes in the graph and configuration (with a single instance) and decides based on that which mode to use.

I've tested on snabb1 that you can now provide an on-a-stick configuration and it'll configure itself in an on-a-stick fashion (I've also tested for bump-in-the-wire). I'd have liked to improve the unit tests around this to make them a bit more robust (especially with adding new instances) - to do that though I think i'd need something like #962.

### CODE REVIEW

File: src/program/lwaftr/run/run.lua [hunk 1]
```diff
@@ -154,31 +154,40 @@ function run(args)
...
+      if opts.virtio_net then
+	 return setup_fn(graph, lwconfig, 'inetNic', 'b4sideNic')
+      end
+
+      -- If instance has external-interface.device configure as bump-in-the-wire
+      -- otherwise configure it in on-a-stick mode.
+      local name, instance = next(lwconfig.softwire_config.instance)
+      local queue = instance.queue.values[1]
+      if queue.external_interface.device then
+	 return setup.load_phy(graph, lwconfig, 'inetNick', 'b4sideNic',
```
Comment (wingo) [inline src/program/lwaftr/run/run.lua]: inetNic

File: src/program/lwaftr/run/run.lua [hunk 2]
```diff
@@ -154,31 +154,40 @@ function run(args)
...
+			       opts.ring_buffer_size)
+      else
+	 local use_splitter = requires_splitter(opts, lwconfig)
+	 local options = {
+	    v4_nic_name = 'inetNic', v6_nic_name = 'b4sideNick',
```
Comment (wingo) [inline src/program/lwaftr/run/run.lua]: b4sideNic

File: src/program/lwaftr/run/run.lua [hunk 3]
```diff
@@ -154,31 +154,40 @@ function run(args)
...
+   local function setup_fn(graph, lwconfig)
+      -- If --virtio has been specified, always use this.
+      if opts.virtio_net then
+	 return setup_fn(graph, lwconfig, 'inetNic', 'b4sideNic')
+      end
+
+      -- If instance has external-interface.device configure as bump-in-the-wire
+      -- otherwise configure it in on-a-stick mode.
+      local name, instance = next(lwconfig.softwire_config.instance)
+      local queue = instance.queue.values[1]
```
Comment (wingo) [inline src/program/lwaftr/run/run.lua:172]: In some future we might want to configure this in a per-instance way, but then again maybe we shouldn't bother :)

**Review by wingo — APPROVED** [review]
Great stuff!  I guess in some future followup we could move the logic as to whether it's on a stick or bump-in-the-wire to setup.lua, but for now this looks quite good enough.
